#!/bin/bash

pwd
hostname
date

conda_path="/home/whitej6/miniforge3/etc/profile.d/conda.sh"
cd /data1/tanseyw/projects/whitej/UnitedPPC/UnitedPPC

job1="init"
job2="pyro"
job3="posterior"
job4="summary"
script1="UnitedPPC.CV_initialization"
script2="UnitedPPC.CV_pyro"
script3="UnitedPPC.CV_posterior"
script4="UnitedPPC.CV_summarization"

cv_opts="--crossval_dims 1 102 --crossval_steps 10 --crossval_folds 10"
svi_opts="--n_steps 2000 --learning_rate 0.001"
# calculate number of jobs in the job array, n_indices = n_folds * len(n_dims_options)
n_indices=110

path_main="/data1/tanseyw/projects/whitej/UnitedPPC"
# data
path_data="${path_main}/data"
file_rna="${path_data}/df_count_inner.csv"
file_zscore="${path_data}/mean_aucs.csv"
file_meta="${path_data}/df_meta_inner.csv"
# results
path_results="${path_main}/results"
path_logs="${path_results}/logs"

# submit trial jobs
echo $(pwd)
echo ${path_results}
echo ${path_logs}
mkdir -p ${path_results} ${path_logs}

# first job of CV_initialization only needs to be run once
# will empty existing cv scores files
jid1=$(
    sbatch \
    --parsable \
    -p componc_cpu \
    -J "${job1}" \
    -N 1 \
    -n 1 \
    -c 10 \
    --mem=10G \
    -t 0:15:00 \
    -o ${path_logs}/${job1}_%j.stdout \
    -e ${path_logs}/${job1}_%j.stderr \
    --wrap="source ${conda_path};\
            conda activate UnitedMet;\
            python3 -m ${script1} \
                    -rna ${file_rna} \
                    -zscore ${file_zscore}
                    -meta ${file_meta} \
                    -rd ${path_results}" \
                    ${cv_opts} \
)

jid2=$(
    sbatch \
    --parsable \
    -p componc_cpu \
    -J "${job2}" \
    --array=1-${n_indices} \
    --depend=afterok:$jid1 \
    -N 1 \
    -n 1 \
    -c 20 \
    --mem=20G \
    -t 1:59:00 \
    -o ${path_logs}/${job2}_%j.stdout \
    -e ${path_logs}/${job2}_%j.stderr \
    --wrap="source ${conda_path}; \
            conda activate UnitedPPC; \
            python3 -m ${script2} \
                    -rd ${path_results} \
                    ${cv_opts} \
                    ${svi_opts}" \
)

jid3=$(
    sbatch \
        --parsable \
        -p componc_cpu \
        -J "${job3}" \
        --array=1-${n_indices} \
        --depend=afterok:$jid2 \
        -N 1 \
        -n 1 \
        -c 24 \
        --mem=96G \
        -t 0:30:00 \
        -o ${path_logs}/${job3}_%j.stdout \
        -e ${path_logs}/${job3}_%j.stderr \
        --wrap="source ${conda_path};\
                conda activate UnitedPPC;\
                python3 -m ${script3} \
                        -rd ${path_results} \
                        ${cv_opts}" \
)

sbatch \
    -p componc_cpu \
    -J "${job4}" \
    --depend=afterok:$jid3 \
    -N 1 \
    -n 1 \
    -c 10 \
    --mem=10G \
    -t 0:15:00 \
    -o ${path_logs}/${job4}_%j.stdout \
    -e ${path_logs}/${job4}_%j.stderr \
    --wrap="source ${conda_path}; \
            conda activate UnitedMet; \
            python3 -m ${script4} \
                    -rd ${path_results} \
                    ${cv_opts}"

echo "cv options:"
echo $opts
echo "Starting job..."
echo "THe path is $PATH"
echo "start time $(date)"